// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  /** Primary D1 database */
  DB: D1Database;
  /** Legacy KV (read-only migration source) */
  cloudmark: KVNamespace;
}
